INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME) VALUES('234', 'rahul');

INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME) VALUES('560', 'ROHAN');

INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME) VALUES('562', 'SAHIL');


INSERT INTO COURSE(COURSE_ID, COURSE_NAME) VALUES('501', 'Spring');

INSERT INTO COURSE(COURSE_ID, COURSE_NAME) VALUES('502', 'React');


INSERT INTO STUDENT_COURSE(STUDENT_ID, COURSE_ID) VALUES('234', '501');

INSERT INTO STUDENT_COURSE(STUDENT_ID, COURSE_ID)VALUES('234', '502');

INSERT INTO STUDENT_COURSE(STUDENT_ID, COURSE_ID) VALUES('560', '501');